push beta4

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -4,28 +4,22 @@
 # INIT
 ######
 
-umask 022
+umask 0022
 
 # Global vars
-TMPDIR=/dev/tmp
-PERSISTDIR=/sbin/.magisk/mirror/persist
+TMPDIR="/dev/tmp"
+PERSISTDIR="/sbin/.magisk/mirror/persist"
 
-rm -rf $TMPDIR 2>/dev/null
-mkdir -p $TMPDIR
+rm -rf "$TMPDIR" 2>/dev/null
+mkdir -p "$TMPDIR"
 
-# echo before loading util_functions
-ui_print() { echo "$1"; }
-
-require_new_magisk() {
-  ui_print "*******************************"
-  ui_print " Please install Magisk v19.0+! "
-  ui_print "*******************************"
-  exit 1
+# Echo before loading util_functions
+ui_print(){ 
+echo "$1"
 }
 
-is_setup_script() {
-  unzip -l "$ZIPFILE" setup.sh | grep -q setup.sh
-  return $?
+load_vksel(){
+. "$MODPATH/addon/Volume-Key-Selector/install.sh"
 }
 
 ####################
@@ -38,12 +32,7 @@ ZIPFILE=$3
 mount /data 2>/dev/null
 
 # Load utility functions
-if [ -f /data/adb/magisk/util_functions.sh ]; then
-  . /data/adb/magisk/util_functions.sh
-  NVBASE=/data/adb
-else
-  require_new_magisk
-fi
+. "/data/adb/magisk/util_functions.sh"
 
 # Preperation for flashable zips
 setup_flashable
@@ -55,11 +44,7 @@ mount_partitions
 api_level_arch_detect
 
 # Setup busybox and binaries
-if $BOOTMODE; then
-boot_actions
-else
-recovery_actions
-fi
+$BOOTMODE && boot_actions || recovery_actions
 
 ##############
 # PREPARATION
@@ -67,117 +52,87 @@ fi
 
 # Extract prop file
 unzip -o "$ZIPFILE" module.prop -d $TMPDIR >&2
-[ ! -f $TMPDIR/module.prop ] && abort "[!] Unable to extract zip file!"
+[ ! -f "$TMPDIR/module.prop" ] && abort "[!] Unable to extract zip file!"
 
+# Mod vars
+NVBASE="/data/adb"
 $BOOTMODE && MODDIRNAME=modules_update || MODDIRNAME=modules
-MODULEROOT=$NVBASE/$MODDIRNAME
-MODID=$(grep_prop id $TMPDIR/module.prop)
-MODPATH=$MODULEROOT/$MODID
-MODNAME=$(grep_prop name $TMPDIR/module.prop)
+MODULEROOT="$NVBASE/$MODDIRNAME"
+MODID="$(grep_prop id $TMPDIR/module.prop)"
+MODPATH="$MODULEROOT/$MODID"
+MODNAME="$(grep_prop name $TMPDIR/module.prop)"
 
 # Create mod paths
 rm -rf "$MODPATH" 2>/dev/null
-mkdir -p $MODPATH
+mkdir -p "$MODPATH"
 
 ##############
 # INSTALLATION
 ##############
 
-# Extract modname_print to $MODPATH
-unzip -o "$ZIPFILE" tx_banner service.sh system.prop -d $MODPATH >&2
-
-if is_setup_script; then
-unzip -oj "$ZIPFILE" module.prop setup.sh uninstall.sh -d $TMPDIR >&2
+# Extract to $MODPATH
+unzip -o "$ZIPFILE" -d "$MODPATH" >&2
 
 # Load install script
-. $TMPDIR/setup.sh
+. "$MODPATH/setup.sh"
 
 # Remove all old files before doing installation if want to
-  if [ "$CLEANSERVICE" = "true" ]; then
-    rm -rf /data/adb/modules/${MODID}/* 2>/dev/null
-  fi
-
-# Enable debugging if true
-  if [ "$DEBUG" = "true" ]; then
-    set -x
-  else
-    set +x
-  fi
-
-# Callback 01
-mod_info_print
-
-# Unzipping under auto extraction
-if [[ "$AUTOUNZIP" = "true" ]]; then
-   if [ -e "$MODPATH/addon" ] ; then
-   unzip -o "$ZIPFILE" 'addon/*' -d $TMPDIR >&2
-
-   elif [ -e "$MODPATH/system" ]; then
-   unzip -o "$ZIPFILE" 'system/*' -d $MODPATH >&2
-   fi
+if [ "$CLEANSERVICE" = "true" ]; then
+rm -rf /data/adb/modules/${MODID}/*
 fi
 
-# Callback 02
-install_module
+# Enable debugging if true
+if [ "$DEBUG" = "true" ]; then
+set -x
+else
+set +x
+fi
 
-# Custom uninstaller
-  if [ -f $TMPDIR/uninstall.sh ]; then 
-    cp -af $TMPDIR/uninstall.sh $MODPATH/uninstall.sh
-  fi
+# Print mod info
+info_print
+
+# Auto vskel load
+if [ "$AUTOVKSEL" = "true" ]; then
+load_vksel
+fi
+
+# Main
+init_main
 
 # Skip mount
-  if [ "$SKIPMOUNT" = "true" ]; then
-    touch $MODPATH/skip_mount
-  fi
-
-# Prop file
-  if [ "$PROPFILE" = "false" ]; then
-    rm -rf $MODPATH/system.prop
-  fi
-
-# Post-fs-data script
-  if [ "$POSTFSDATA" = "false" ]; then
-    rm -rf $MODPATH/post-fs-data.sh
-  fi
-
-# Service script
-  if [ "$LATESTARTSERVICE" = "false" ]; then
-    rm -rf $MODPATH/service.sh
-  fi
-
-# Module info
-cp -af $TMPDIR/module.prop $MODPATH/module.prop
+if [ "$SKIPMOUNT" = "true" ]; then
+touch "$MODPATH/skip_mount"
+fi
 
 # Set permissions
 set_permissions
 
-else
-ui_print "[*] Module setup script not found, exiting installation..."
-exit 1
-fi
+# Do cleanup
+do_cleanup
 
 # Handle replace folders
 for TARGET in $REPLACE; do
-  ui_print "[*] Replace target: $TARGET"
-  mktouch $MODPATH$TARGET/.replace
+ui_print "[*] Replace target: $TARGET"
+mktouch "$MODPATH$TARGET/.replace"
 done
 
 if $BOOTMODE; then
-  # Update info for Magisk Manager
-  mktouch $NVBASE/modules/$MODID/update
-  cp -af $MODPATH/module.prop $NVBASE/modules/$MODID/module.prop
+# Update info for Magisk app
+mktouch $NVBASE/modules/$MODID/update
+cp -af "$MODPATH/module.prop" "$NVBASE/modules/$MODID/module.prop"
 fi
 
 # Copy over custom sepolicy rules
-if [ -f $MODPATH/sepolicy.rule -a -e $PERSISTDIR ]; then
-  ui_print "[*] Installing custom sepolicy patch"
-  PERSISTMOD=$PERSISTDIR/magisk/$MODID
-  mkdir -p $PERSISTMOD
-  cp -af $MODPATH/sepolicy.rule $PERSISTMOD/sepolicy.rule
+if [ -f "$MODPATH/sepolicy.rule" ]; then
+ui_print "[*] Installing custom sepolicy rules"
+copy_sepolicy_rules
 fi
 
 # Remove stuffs that don't belong to modules
-rm -rf $MODPATH/LICENSE
+rm -rf "$MODPATH/META-INF"
+rm -rf "$MODPATH/addon"
+rm -rf "$MODPATH/setup.sh"
+rm -rf "$MODPATH/system/placeholder"
 
 ##############
 # Finalizing
@@ -187,7 +142,14 @@ cd /
 if ! $BOOTMODE; then
 recovery_cleanup
 fi
-rm -rf $TMPDIR
+rm -rf "$TMPDIR"
 
-ui_print "[*] Done"
+if [[ "$MULTILANGSUPPORT" == "true" ]]; then
+ if [[ $LANG == *"ar-*"* ]]; then
+  ui_print "[*] تم الإنهاء"
+ else
+  ui_print "[*] Done"
+ fi
+fi
+
 exit 0
